import prisma from "@/app/components/lib/prisma";
import { updateMemo } from "@/app/action/action-memo";
import FormMemo from "@/app/components/memo/FormMemo";
import DeleteModal from "@/app/components/memo/DeleteMemoModal";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "個別のメモ",
  description: "Generated by create next app",
};

const Page = async ({
  params,
}: {
  params: { memo_id: string; itineraryHome_id: string };
}) => {
  const id = Number(params.memo_id);
  const itineraryHomeId = Number(params.itineraryHome_id);

  const updateMemoWidthId = updateMemo.bind(null, id);

  const memo = await prisma.memo.findUnique({
    where: {
      id,
    },
  });

  return (
    <main>
      <div className="main-contents-area">
        <div className="contents-area">
          <div>
            <FormMemo
              formAction={updateMemoWidthId}
              memo={memo}
              buttonName="保存"
              itineraryHomeId={itineraryHomeId}
            />
          </div>
          <div>
            <DeleteModal memo={memo} itineraryHomeId={itineraryHomeId} />
          </div>
        </div>
      </div>
    </main>
  );
};

export default Page;
