import { addItinerary } from "@/app/action/action-itinerary";
import FormItinerary from "@/app/components/itinerary/FormItinerary";
import ListItinerary from "@/app/components/itinerary/ListItinerary";
import { Metadata } from "next";
import prisma from "@/app/components/lib/prisma";
import getCurrentUser from "@/app/action/getCurrentUser";

export const metadata: Metadata = {
  title: "旅程表アプリ",
  description: "Generated by create next app",
};

const Page = async ({ params }: { params: { itineraryHome_id: string } }) => {
  const id = Number(params.itineraryHome_id);
  const currentUser = await getCurrentUser();
  const userId = currentUser?.id;

  const itineraryHome = await prisma.itineraryHome.findUnique({
    where: {
      id,
    },
    include: {
      itineraries: true,
    },
  });

  return (
    <main>
      <div className="main-contents-area">
        <div className="contents-area">
          <div>
            <FormItinerary
              buttonName="旅程を追加"
              formAction={addItinerary}
              itineraryHomeId={itineraryHome?.id}
              userId={userId}
            />
          </div>
          <div>
            <ListItinerary
              itineraries={itineraryHome?.itineraries}
              itineraryHomeId={itineraryHome?.id}
            />
          </div>
        </div>
      </div>
    </main>
  );
};

export default Page;
