import prisma from "@/app/components/lib/prisma";
import { Metadata } from "next";
import FormItineraryHome from "@/app/components/itineraryHome/FormItineraryHome";
import { updateItineraryHome } from "@/app/action/action-ItineraryHome";
import DeleteItineraryHomeModal from "@/app/components/itineraryHome/DeleteItineraryHomeModal";
import getCurrentUser from "@/app/action/getCurrentUser";

export const metadata: Metadata = {
  title: "個別の旅行",
  description: "Generated by create next app",
};

const Page = async ({ params }: { params: { itineraryHome_id: string } }) => {
  const id = Number(params.itineraryHome_id);
  const updateItineraryHomeWidthId = updateItineraryHome.bind(null, id);
  const currentUser = await getCurrentUser();
  const userId = currentUser?.id

  const itineraryHome = await prisma.itineraryHome.findUnique({
    where: {
      id,
    },
  });

  return (
    <main>
      <div className="main-contents-area">
        <div className="contents-area">
          <div>
            <FormItineraryHome
              formAction={updateItineraryHomeWidthId}
              itineraryHome={itineraryHome}
              buttonName="保存"
              userId={userId}
            />
          </div>
          <div>
            <DeleteItineraryHomeModal itineraryHome={itineraryHome} />
          </div>
        </div>
      </div>
    </main>
  );
};

export default Page;
