import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideMenu from "../../components/blog/SideMenu";
import Header from "../../components/Header";
import Footer from "../../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="bg-gray-100">{children}</div>
    </>
  );
}
