import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ToastContext from "@/app/context/ToastContext";
import AuthContext from "@/app/context/AuthContext";
import AuthGuard from "@/app/components/auth/authGuard/BlogAuthGuard";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <AuthContext>
        <AuthGuard>
          <ToastContext />
          <div className="bg-sky-50 py-8">
            <div className="max-w-[1150px] flex justify-center items-center mx-auto bg-white">
              <div className="w-full p-4">{children}</div>
            </div>
          </div>
        </AuthGuard>
      </AuthContext>
    </>
  );
}
