import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="bg-sky-50">
        <div className="max-w-screen-lg flex justify-center items-center mx-auto bg-white">
          <div className="w-full p-4">{children}</div>
        </div>
      </div>
    </>
  );
}
