import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideMenu from "../../components/blog/SideMenu";
import Header from "../../components/Header";
import Footer from "../../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="bg-sky-50">
        <div className="max-w-screen-lg mx-auto flex flex-col md:flex-row mb-8">
          <div className="w-full md:w-3/4 bg-white rounded p-4 mr-8 ">
            {children}
          </div>
          <div className="w-full md:w-1/4 py-4 bg-white rounded  ">
            <SideMenu />
          </div>
        </div>
      </div>
    </>
  );
}
