import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import AuthContext from "./context/AuthContext";
import getCurrentUser from "./action/getCurrentUser";
import Navigation from "./components/auth/navigation/Navigation";
import SignupModal from "./components/auth/authUi/SignupModal";
import ToastContext from "./context/ToastContext";
import LoginModal from "./components/auth/authUi/LoginModal";

config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="jp">
      <body className={inter.className}>
        <AuthContext>
          <ToastContext />
          <SignupModal />
          <LoginModal />
          <Navigation currentUser={currentUser} />
          {children}
        </AuthContext>
      </body>
    </html>
  );
}
