import ItineraryAuthGuard from "@/app/components/auth/authGuard/ItineraryAuthGuard";
import { Metadata } from "next";
import getCurrentUser from "@/app/action/getCurrentUser";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const currentUser = await getCurrentUser();

  return (
    <>
      <ItineraryAuthGuard currentUser={currentUser}>
        {children}
      </ItineraryAuthGuard>
    </>
  );
}
