import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideMenu from "../../components/blog/SideMenu";
import Header from "../../components/Header";
import Footer from "../../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <div className="bg-gray-100">
        <div className="max-w-screen-lg  mx-auto flex flex-col md:flex-row">
          <div className="w-full md:w-3/4 py-4">{children}</div>
          <div className="w-full md:w-1/4 py-4">
            <SideMenu />
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}
