import { addDashboardMemo } from "@/app/action/action-dashboard";
import { Metadata } from "next";
import FormDashboardMemo from "@/app/components/blog/dashboard/FormDashboardMemo";
import ListDashboardMemo from "@/app/components/blog/dashboard/ListDashboardMemo";

export const metadata: Metadata = {
  title: "ダッシュボード",
  description: "Generated by create next app",
};

const Memo = async () => {
  return (
    <>
      <ListDashboardMemo />
      <FormDashboardMemo formAction={addDashboardMemo} buttonName="追加" />
    </>
  );
};

export default Memo;
