import ListMemo from "@/app/components/memo/ListMemo";
import { addMemo } from "@/app/action/action-memo";
import FormMemo from "@/app/components/memo/FormMemo";
import FormMemoModal from "@/app/components/memo/FormMemoModal";
import { Metadata } from "next";
import prisma from "@/app/components/lib/prisma";

export const metadata: Metadata = {
  title:  'メモ帳アプリ',
  description: "Generated by create next app",
};

const Page = async ({ params }: { params: { itineraryHome_id: string } }) => {
  const id = Number(params.itineraryHome_id);

  const itineraryHome = await prisma.itineraryHome.findUnique({
    where: {
      id,
    },
    include: {
      memos: true,
    },
  });

  return (
    <main>
      <div className="main-contents-area">
        <div className="contents-area">
          <div>
            <FormMemo memos={itineraryHome?.memos} itineraryHomeId={itineraryHome?.id} formAction={addMemo} buttonName="追加" />
          </div>
          <div>
            <ListMemo memos={itineraryHome?.memos} itineraryHomeId={itineraryHome?.id}/>
            <FormMemoModal  formAction={addMemo} buttonName="追加" />
          </div>
        </div>
      </div>
    </main>
  );
};

export default Page;
