import prisma from "@/app/components/lib/prisma";
import { updateItinerary } from "@/app/action/action-itinerary";
import FormItinerary from "@/app/components/itinerary/FormItinerary";
import DeleteItineraryModal from "@/app/components/itinerary/DeleteItineraryModal";
import { Metadata } from "next";

export const metadata: Metadata = {
  title:  '個別の旅程',
  description: "Generated by create next app",
};


const page = async ({ params }: { params: { id: string } }) => {
  const id = Number(params.id);
  const updateItineraryWithId = updateItinerary.bind(null, id);
  const itinerary = await prisma.itinerary.findUnique({
    where: {
      id,
    },
  });

  return (
    <main>
      <div className="main-contents-area">
        <div className="contents-area">
          <div>
            <FormItinerary
              itinerary={itinerary}
              formAction={updateItineraryWithId}
              buttonName={"保存"}
            />
          </div>
          <div>
            <DeleteItineraryModal itinerary={itinerary} />
          </div>
        </div>
      </div>
    </main>
  );
};

export default page;
