import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import AuthContext from "../context/AuthContext";
import getCurrentUser from "../action/getCurrentUser";
import SignupModal from "../components/auth/authUi/SignupModal";
import ToastContext from "../context/ToastContext";
import LoginModal from "../components/auth/authUi/LoginModal";
import FooterMenu from "../components/FooterMenu";
import Footer from "../components/Footer";
import HeaderItinerary from "../components/HeaderItinerary";

config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "国内旅行・海外旅行のしおりアプリ「旅のメモリーブック」",
    template: "%s | 旅のメモリーブック",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();

  return (
    <>
      <AuthContext>
        <ToastContext />
        <SignupModal />
        <LoginModal />
        <HeaderItinerary currentUser={currentUser} />
        {children}
        <Footer />
        <FooterMenu />
      </AuthContext>
    </>
  );
}
